workflows:
  expo-android-debug:
    name: Expo Android (Debug APK)
    # Thư mục chứa source code (trong repo của bạn là 1-a1d7fc488bac)
    working_directory: 1-a1d7fc488bac

    environment:
      node: 20
      java: 17
      vars:
        EXPO_NO_TELEMETRY: "1"

    cache:
      cache_paths:
        - ~/.npm
        - $CM_BUILD_DIR/**/node_modules
        - $CM_BUILD_DIR/**/.gradle

    scripts:
      - name: Cài dependencies
        script: npm install

      - name: Tạo thư mục android/ bằng Expo Prebuild
        script: npx expo prebuild -p android --non-interactive

      - name: Build APK debug
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - 1-a1d7fc488bac/android/app/build/outputs/apk/debug/app-debug.apk
