workflows:
  react-native-android:
    name: Build React Native Android
    environment:
      node: latest
      npm: true
      java: 17
      groups:
        - keystore_credentials
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
